### ISSUE TITLE
Investigate How React Apps Can Support Path-Based Proxy/Gateway

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms#108]
To run Ego UI behind a reverse proxy or gateway (e.g. http://<domain>/ego-ui) will not work with how Ego UI currently serves its static assets.  The assets are assumed to be always at the root of the domain (e.g. /static/main.js instead of /ego-ui/static/main.js).

Because Create React App functionality only supports overriding the public URL at run-time, this does not help us because Ego-UI needs to be consumed by different parties with different approaches (we need to be able to override somehow at build time).

This may also be an issue for the other React Apps, Arranger UI, DMS UI.

Need to investigate & possibly test a solution to support the path-based proxy for the 3 React Apps.  Time-box to 2-3 days, and if viable solution cannot be found, we may need to go with a sub-domain based proxy instead.

**Comment by andricDu** [comment]
Ego-UI has been updated to support PUBLIC_URL environment variable. The dockerfile has been refactored to not include nginx.

**Comment by b-f-chan** [comment]
Ego-UI, Arranger-UI, DMS-UI have all been updated to support the path-based gateway.  Gateway has been unblocked and now implemented with sub-paths and available for internal testing.  Closing this ticket.
