### ISSUE TITLE
Investigate Daemon Attaching to Network Failure Error

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms#116]
Investigate the daemon attaching to network failure error seen on @christinayung VM in DMS 0.13.1:

```
Status: Downloaded newer image for overture/dms:0.12.1
docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded.
```

This is after simply executing ```dms-h```, no config has even been built yet.  Not sure why it is trying to download image 0.12.1.

Here is a potential thread to investigate:
https://stackoverflow.com/questions/57388405/error-response-from-daemon-attaching-to-network-failed-make-sure-your-network

**Comment by christinayung** [comment]
I can reproduce the error by performing the following on a new VM
* install Docker using: `sudo snap install docker`
* `sudo groupadd docker`
* `sudo usermod -aG docker $USER`
* `sudo reboot`
* `curl https://raw.githubusercontent.com/overture-stack/dms/0.15.1/src/main/bin/dms-docker > dms`
* `chmod +x dms`
* `docker swarm init`
* `dms -h`
* Got the error: 
`Status: Downloaded newer image for overture/dms:0.15.1
docker: Error response from daemon: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded.`

This confirmed that Docker must be installed using the official Ubuntu instructions on https://docs.docker.com/engine/install/ubuntu/

**Comment by b-f-chan** [comment]
Adding as common problem to DMS installer documentation

**Comment by blabadi** [comment]
is there any other action here on our side ?

**Comment by b-f-chan** [comment]
No action, this is a documentation update now

**Comment by b-f-chan** [comment]
Documented in "Common Problems" section of DMS Admin Guide, closing
