### ISSUE TITLE
Refactor and Cleanup Prototype

### ISSUE THREAD

**Issue by rtisma** [overture-stack/dms#30]
The prototype that simply asks questions and deploy ego needs some refactoring and cleanup. This includes
- logging
- fix maven warnings/lint
- proper terminal printing and abstraction
- fix package organization
- refactor classes to follow proper SOLID principles. Right now they are kinda POCs, just to get something working. 
- change Spec to Config, and "config Spec" to "build config"

This will lay the foundation for other tickets to follow, as alot of files and variables need to be renamed and moved around.

NOTE: Include testing here

**Comment by b-f-chan** [comment]
Note: Rename spec to config!

**Comment by b-f-chan** [comment]
Discussed with @rtisma - Linting not complete but it is just 1 warning - Can treat as separate ticket later <TBD> to fix warnings/linting

PRs postponed until prototype complete - Can do full audit at that point
