### ISSUE TITLE
Ego post deployment initialization

### ISSUE THREAD

**Issue by rtisma** [overture-stack/dms#32]
This involves configuring ego with the sysadmin user and the dms application clientId and clientSecret, which will be used to configuring the dms-ui, score, song, and ego-ui

**Comment by b-f-chan** [comment]
Boostrap EGO post deployment for users

**Comment by b-f-chan** [comment]
PR review should be done as each component completes - Discuss with @rtisma when he returns

**Comment by b-f-chan** [comment]
This is done and working, but needs code review

**Comment by b-f-chan** [comment]
As discussed in planning, we will close each component's implementation ticket and create separate tickets to log bugs in testing, to avoid carrying the implementation ticket continuously through each sprint.

EGO component has been code reviewed and sanity tested - Script downloads the image, questions & inputs are in the script, and deploy command attempts to deploy the service.
