### ISSUE TITLE
Implement Provisioning for Song

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms#5]
## Objective
Create the interactive questions for SONG service deployment, and deploy\
- inludes database deployment

## Outcome
Should be able to configure SONG and deploy it locally.

## Wiki Link
https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-TableofContents

**Comment by b-f-chan** [comment]
Sprint 10 candidate - If EGO installer step is completed in Sprint 9, we may be able to parallelize work with EGO as the template.  @rtisma needs to setup the Gateway, in the meantime, perhaps @anncatton can take on the next component (e.g. SONG).  To be discussed in planning.

**Comment by b-f-chan** [comment]
Closing, duplicate of #35
