### ISSUE TITLE
Implement DMS Gateway / Server Mode

### ISSUE THREAD

**Issue by rtisma** [overture-stack/dms#9]
# Objective
Implement the gateway so it can be configured via the installer

The gateway would be setup in Production Mode only to expose only traffic from only a single port which would be routed to specific service URLs in docker

# Outcome
DMS gateway deployment that routes traffic from a single port to the different docker services. Should follow
https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-DMSClusterDiagram

# Additional Requirements:

- Production mode must capture registered domain
- Production mode must capture Ego redirect URI

**Comment by b-f-chan** [comment]
Sprint 10 candidate - If EGO installer step is completed in Sprint 9, we may be able to parallelize work with EGO as the template.  @rtisma needs to setup the Gateway, in the meantime, perhaps @anncatton can take on the next component (e.g. SONG).  To be discussed in planning.

**Comment by akachru-github** [comment]
- Dockerized nginx.

**Comment by b-f-chan** [comment]
Path-based proxy implemented in both local and server mode

Local and server mode deployment tested on Collab VM, both deploy services successfully and are accessible via sub-path (via localhost in local mode, via configured domain in server mode)

Scope of ticket complete, bugs shall be logged in separate tickets, closing
